# Generated by Django 4.1.4 on 2022-12-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_aboutus_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='enquiryDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
