# Generated by Django 4.1.4 on 2022-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_service_service_img_alter_contact_enquirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='creationsDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
